language: node_js
node_js:
  - "19"
  - node
services:
  - docker

before_install:
  - docker build -t natcobbinah/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true natcobbinah/docker-react npm run test