language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t natcobbinah/docker-react-demo -f Dockerfile.dev .

script:
  - docker run natcobbinah/docker-react-demo npm run test -- --coverage